### ISSUE TITLE
Compose containers need to be downed before being started

### ISSUE THREAD

**Issue by ADRFranklin** [picostack/pico#19]
Containers are failing to be started, because a port allocation already exists, so I feel the containers should be stopped before they are then started again.

Right now it is impossible for me to make continuous updates to a repo, because the docker container fails to be brought back up again.

**Comment by Southclaws** [comment]
Wadsworth isn't tightly bound to compose (this is the main reason Wadsworth was built as a successor to Machinehead) so I'm unsure on how to solve this.

One thing is for sure, that doesn't sound like normal compose behaviour. I have many containers bound to ports and they restart perfectly fine. This is because when you run `docker-compose up` on an already running, but outdated stack, Compose runs a diff against the existing state and the new state to figure out if it should restart the containers - and if so, it will handle the takedown and bringup itself (this is one of the nice features of Compose).

I'm not sure how Wadsworth can assist in this.
